version: "3.9"

services:
  tests:
    build: .
    image: pw-bdd
    environment:
      CI: "1"
      NO_COLOR: "1"
      TZ: America/Sao_Paulo
    volumes:
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results
      - ./.features-gen:/app/.features-gen
    command: ["npm", "run", "test"]

