name: Playwright Docker CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare report directories
        run: |
          mkdir -p playwright-report test-results .features-gen
          chmod -R 777 playwright-report test-results .features-gen

      - name: Build test image
        run: docker build -t pw-bdd .

      - name: Run Playwright tests in Docker
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/playwright-report:/app/playwright-report" \
            -v "${{ github.workspace }}/test-results:/app/test-results" \
            -v "${{ github.workspace }}/.features-gen:/app/.features-gen" \
            pw-bdd

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore

      - name: Upload Step Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          if-no-files-found: ignore

